after-login-command = []
after-startup-command = []
start-at-login = true 

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 40
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = 'move-mouse window-lazy-center'

automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.bottom = 5
outer.top = 5
outer.right = 5
outer.left = 5

[mode.main.binding]
alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
alt-l = 'focus --boundaries-action wrap-around-the-workspace right'
alt-left = 'focus --boundaries-action wrap-around-the-workspace left'
alt-down = 'focus --boundaries-action wrap-around-the-workspace down'
alt-up = 'focus --boundaries-action wrap-around-the-workspace up'
alt-right = 'focus --boundaries-action wrap-around-the-workspace right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'
alt-shift-left = 'move left'
alt-shift-down = 'move down'
alt-shift-up = 'move up'
alt-shift-right = 'move right'

alt-enter = 'fullscreen'
alt-shift-enter = 'macos-native-fullscreen'

alt-s = 'layout tiles accordion' 
alt-e = 'layout horizontal vertical' 

alt-space = 'layout floating tiling' 
alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'

alt-b = 'workspace Browser'
alt-t = 'workspace Terminal'
alt-g = 'workspace Google'
alt-m = 'workspace Meet'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'

alt-shift-b = 'move-node-to-workspace Browser'
alt-shift-t = 'move-node-to-workspace Terminal'
alt-shift-g = 'move-node-to-workspace Google'
alt-shift-m = 'move-node-to-workspace Meet'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-a = 'focus-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'
#alt-r = 'mode resize'

[mode.service.binding]
esc = ['reload-config', 'mode main']
h = ['join-with left', 'mode main']
j = ['join-with down', 'mode main']
k = ['join-with up', 'mode main']
l = ['join-with right', 'mode main']
r = ['flatten-workspace-tree', 'mode main']

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace Browser'

[[on-window-detected]]
if.app-id = 'com.googlecode.iterm2'
run = 'move-node-to-workspace Terminal'

[[on-window-detected]]
if.app-name-regex-substring = 'Gmail|(Google (Calendar|Chat))'
run = 'move-node-to-workspace Google'

[[on-window-detected]]
if.app-name-regex-substring = 'Google Meet'
run = 'move-node-to-workspace Meet'
