- name: Cleanup folke/lazy.git
  ansible.builtin.file:
    path: $HOME/.local/share/nvim/lazy
    state: absent
- name: Install folke/lazy.git
  ansible.builtin.git:
    repo: https://github.com/folke/lazy.nvim.git
    version: stable
    update: yes
    dest: $HOME/.local/share/nvim/lazy
  notify:
    - Sync Nvim
