- name: Install folke/lazy.git
  ansible.builtin.git:
    repo: https://github.com/folke/lazy.nvim.git
    version: stable
    depth: 1
    update: yes
    dest: $HOME/.local/share/nvim/lazy
  notify:
    - Sync Nvim
