#!/bin/zsh

USER_PROMPT='%F{green}%n%f'
HOSTNAME_PROMPT='%F{white}%m%f'
DIRECTORY_PROMP='%F{blue}%~%f%b'
RETURN_CODE_PROMPT=' %(?..[%F{red}%?%f])'
NEWLINE_PROMPT=$'\n'
PROMPT=$USER_PROMPT'@'$HOSTNAME_PROMPT
PROMPT=$PROMPT':'$DIRECTORY_PROMP$RETURN_CODE_PROMPT$NEWLINE_PROMPT
# PROMPT=$DIRECTORY_PROMP$RETURN_CODE_PROMPT$NEWLINE_PROMPT
PROMPT=$PROMPT'%(!.#.$) '
# PROMPT=$PROMPT'%(!.#.%F{green}'$'\ue285''%f) '
