# export PATH="/usr/local/opt/python/libexec/bin:$HOME/bin:$HOME/.local/bin:/usr/local/bin:/usr/bin:$PATH"
export PATH="$PATH:/usr/local/opt/llvm/bin"
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export VISUAL=nvim
export EDITOR="$VISUAL"

[[ $OSTYPE == darwin* ]] && export BROWSER='open'

# export PAGER="most"
# export MANPAGER="moar --style xcode --no-linenumbers --no-statusbar"
export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=1000000
export SAVEHIST=1000000
