# setopt CORRECT_ALL
setopt AUTO_CD
setopt BANG_HIST
setopt CORRECT
setopt EXTENDED_GLOB
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
setopt INTERACTIVE_COMMENTS
setopt MENU_COMPLETE
setopt SHARE_HISTORY
unsetopt BEEP

# vim keymap
bindkey -v

# habit of ctrl-a and ctrl-e in shell
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line

fpath=($XDG_CONFIG_HOME/zsh/functions $fpath)
autoload -Uz mvbck cpbck strip

autoload -Uz colors && colors

zstyle ':completion:*' menu select
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "$HOME/.zsh_cache"

# aliases
source $XDG_CONFIG_HOME/zsh/aliases.zsh

# prompt
source $XDG_CONFIG_HOME/zsh/prompt.zsh

#plugins
source $XDG_CONFIG_HOME/zsh/plugins.zsh
